import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
const nav=[['general','Vista general','◈'],['monitor','Monitoreo','⌁'],['assets','Activos y áreas','▦'],['events','Anomalías','!'],['rules','Reglas y umbrales','≡'],['analysis','Análisis','↗'],['reports','Informes','▤'],['simulation','Simulación','▷'],['users','Usuarios y permisos','♙'],['settings','Configuración y salud','⚙']];
const fmt=(v,d=3)=>v===null||v===undefined?'No disponible':Number(v).toLocaleString('es-GT',{maximumFractionDigits:d,minimumFractionDigits:d});
const num=x=>typeof x==='number'?fmt(x):x??'No calculable';
const units={current:'A',power:'kW',voltage:'V'};
const vars={current:'Corriente',power:'Potencia',voltage:'Voltaje'};
async function request(url,body){const r=await fetch(url,{credentials:'same-origin',...(body!==undefined?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Object.assign(new Error(d.error),{status:r.status});return d;}
function Field({label,children}){return <label className="field"><span>{label}</span>{React.isValidElement(children)&&['input','select'].includes(children.type)?React.cloneElement(children,{'aria-label':label}):children}</label>}
function Card({title,value,unit='',hint='',tone=''}){return <article className={'metric '+tone}><small>{title}</small><strong>{value} <em>{unit}</em></strong><span>{hint}</span></article>}
function Table({heads,rows,empty='No hay registros para mostrar.'}){return <div className="table-wrap"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>):<tr><td colSpan={heads.length} className="empty">{empty}</td></tr>}</tbody></table></div>}
function Badge({children,tone=''}){return <span className={'badge '+tone}>{children}</span>}
function Chart({rows,variable='power',unit='kW',title='Potencia recibida',threshold=null}){
 if(!rows.length)return <section className="panel"><h2>{title}</h2><div className="empty">Sin mediciones recibidas para este período.</div></section>;
 const sorted=[...rows].sort((a,b)=>Date.parse(a.at)-Date.parse(b.at)).slice(-80);const max=Math.max(...sorted.map(m=>m[variable]),threshold||0,0.01)*1.15;const points=sorted.map((m,i)=>`${52+(i/(sorted.length-1||1))*690},${210-m[variable]/max*170}`).join(' ');return <section className="panel"><div className="panel-title"><h2>{title}</h2><Badge>{unit}</Badge></div><svg role="img" aria-label={`${title}, ${sorted.length} mediciones, unidad ${unit}`} viewBox="0 0 780 255">{[0,1,2,3,4].map(i=><g key={i}><line x1="52" x2="742" y1={210-i*42.5} y2={210-i*42.5} stroke="#dce6ed"/><text x="5" y={215-i*42.5} fill="#68808e" fontSize="12">{fmt(max*i/4,1)}</text></g>)}<polygon points={`52,210 ${points} 742,210`} fill="#e3f1f5"/><polyline points={points} fill="none" stroke="#1483a3" strokeWidth="3"/>{threshold!==null&&<><line x1="52" x2="742" y1={210-threshold/max*170} y2={210-threshold/max*170} stroke="#c58b21" strokeDasharray="8 6"/><text x="560" y={200-threshold/max*170} fill="#b17811">Umbral {threshold} {unit}</text></>}<text x="52" y="240" fontSize="12" fill="#68808e">{new Date(sorted[0].at).toLocaleTimeString('es-GT')}</text><text x="670" y="240" fontSize="12" fill="#68808e">{new Date(sorted.at(-1).at).toLocaleTimeString('es-GT')}</text></svg></section>;
}
function App(){
 const [data,setData]=useState(null),[view,setView]=useState('general'),[error,setError]=useState(''),[toast,setToast]=useState(''),[auth,setAuth]=useState(false),[loading,setLoading]=useState(true),[mobile,setMobile]=useState(false),[busy,setBusy]=useState(false),[editor,setEditor]=useState(null),[selected,setSelected]=useState('PM-001'),[tab,setTab]=useState(0),[event,setEvent]=useState(null),[filters,setFilters]=useState({from:'',to:'',point:'',area:''}),[draftFilters,setDraftFilters]=useState({from:'',to:'',point:'',area:''});
 function query(f=filters){const q=new URLSearchParams();for(const [k,v]of Object.entries(f))if(v)q.set(k,k==='from'||k==='to'?new Date(v).toISOString():v);return q.toString();}
 const time=t=>t?new Intl.DateTimeFormat('es-GT',{timeZone:data?.settings?.timezone||'America/Guatemala',dateStyle:'short',timeStyle:'medium'}).format(new Date(t)):'Sin datos';
 async function refresh(){try{const d=await request('/api/state?'+query());setData(d);setAuth(true);setError('');}catch(e){if(e.status===401){setAuth(false);setData(null);}else setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{refresh();const t=setInterval(refresh,2500);return ()=>clearInterval(t);},[JSON.stringify(filters)]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t);}},[toast]);
 const admin=data?.user.role==='Administrador',canReport=admin||data?.user.role==='Técnico';
 async function save(route,b){setBusy(true);setError('');try{await request(route,b);setEditor(null);setToast('Cambios guardados.');await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function login(e){e.preventDefault();setBusy(true);const f=new FormData(e.target);try{await request('/api/login',{username:f.get('username'),password:f.get('password')});await refresh();setView('general');setError('');}catch(e){setError(e.message);}finally{setBusy(false);}}
 function go(id){setView(id);setTab(0);setMobile(false);setEvent(null);}
 if(loading)return <main className="loading">Cargando sistema…</main>;
 if(!auth||!data)return <main className="login"><div className="login-art"><div className="brand">ENERGÍA<span>CONTROL Y ANÁLISIS</span></div><h1>Conoce el consumo.<br/>Anticipa las anomalías.</h1><p>Sistema de monitoreo y gestión del consumo energético en edificios.</p><div className="signal">▁ ▃ ▂ ▅ ▄ ▆ ▅ █ ▆</div><Badge>PG2 · SIMULACIÓN</Badge></div><section className="login-form"><small>ACCESO AL SISTEMA</small><h2>Iniciar sesión</h2><p>Ingresa con tu cuenta y grupo autorizado.</p>{error&&<div role="alert" className="alert">{error}</div>}<form onSubmit={login}><Field label="Usuario"><input name="username" autoComplete="username" required/></Field><Field label="Contraseña"><input name="password" type="password" autoComplete="current-password" required/></Field><button className="primary" disabled={busy}>{busy?'Validando…':'Ingresar al sistema →'}</button></form><p className="muted">La cuenta inicial se indica en la consola al ejecutar el programa.</p></section></main>;
 const point=data.points.find(p=>p.id===selected)||data.points[0],rows=data.measurements,pointRows=rows.filter(m=>m.pointId===point?.id),active=data.points.filter(p=>p.communication==='Vigente'),open=data.events.filter(e=>e.status!=='Cerrada');
 const groupRows=rows.reduce((a,m)=>{let g=a.find(x=>x.at===m.at);if(!g){g={at:m.at,power:0};a.push(g);}g.power+=m.power;return a;},[]);
 const commonFilters=<form className="filters" onSubmit={e=>{e.preventDefault();try{query(draftFilters);setFilters({...draftFilters});}catch{setError('Fechas inválidas.');}}}><Field label="Desde"><input type="datetime-local" value={draftFilters.from} onChange={e=>setDraftFilters({...draftFilters,from:e.target.value})}/></Field><Field label="Hasta"><input type="datetime-local" value={draftFilters.to} onChange={e=>setDraftFilters({...draftFilters,to:e.target.value})}/></Field><Field label="Punto"><select value={draftFilters.point} onChange={e=>setDraftFilters({...draftFilters,point:e.target.value})}><option value="">Todos los puntos</option>{data.points.map(p=><option key={p.id} value={p.id}>{p.id} · {p.name}</option>)}</select></Field><Field label="Área"><select value={draftFilters.area} onChange={e=>setDraftFilters({...draftFilters,area:e.target.value})}><option value="">Todas las áreas</option>{data.areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><button className="primary">Aplicar filtros</button><button type="button" onClick={()=>{setDraftFilters({from:'',to:'',point:'',area:''});setFilters({from:'',to:'',point:'',area:''});}}>Limpiar</button></form>;
 const pointTable=(editable=false)=><Table heads={['Punto / activo','Área','Corriente','Potencia','Comunicación','Última recepción',...(editable?['Acción']:[])]} rows={data.points.map(p=>[<><b>{p.id}</b><small className="block">{p.name}</small></>,data.areas.find(a=>a.id===p.areaId)?.name,`${fmt(p.last?.current)} A`,`${fmt(p.last?.power)} kW`,<Badge tone={p.communication==='Vigente'?'good':'warn'}>{p.communication}</Badge>,time(p.lastReceived),...(editable?[<button onClick={()=>setEditor({type:'point',values:{...p,edit:true}})}>Editar</button>]:[])])}/>;
 let content;
 if(view==='general')content=<><div className="metrics"><Card title="POTENCIA ACTUAL" value={active.length?fmt(active.reduce((s,p)=>s+(p.last?.power||0),0)):'No disponible'} unit="kW" hint="Solo puntos con comunicación vigente"/><Card title="ENERGÍA RECIBIDA" value={data.analysis.rows?fmt(data.analysis.energy,5):'No disponible'} unit="kWh" hint="Acumulación en el período filtrado"/><Card title="COBERTURA DE RECEPCIÓN" value={num(data.analysis.coverage)} unit="%" hint={`${data.analysis.rows} / ${data.analysis.expected} mensajes`} tone="green"/><Card title="ANOMALÍAS ABIERTAS" value={open.length} hint="Eventos pendientes de cierre" tone="amber"/></div>{commonFilters}<div className="grid-main"><Chart rows={groupRows} title="Potencia agregada recibida"/><section className="panel"><h2>Estado operativo</h2><div className="stat"><span>Dispositivos vigentes</span><strong>{active.length} / {data.points.filter(p=>p.active).length}</strong></div><div className="stat"><span>Comunicación MQTT</span><Badge tone={data.health.mqtt?'good':'warn'}>{data.health.mqtt?'Conectada':'Sin conexión'}</Badge></div><div className="stat"><span>Simulación</span><strong>{data.health.running?'En ejecución':'Pausada'}</strong></div><p className="muted">Los datos representan escenarios de prueba. La vigencia depende de la hora de recepción.</p>{admin&&<button className="primary" onClick={()=>go('simulation')}>Abrir simulador →</button>}</section></div><section className="panel"><h2>Puntos de medición</h2>{pointTable()}</section></>;
 if(view==='monitor')content=<><div className="toolbar"><Field label="Punto de medición"><select value={point?.id||''} onChange={e=>setSelected(e.target.value)}>{data.points.map(p=><option key={p.id}>{p.id}</option>)}</select></Field></div>{commonFilters}<div className="grid-main"><Chart rows={pointRows} variable="current" unit="A" title="Corriente RMS recibida" threshold={data.rules.find(r=>r.active&&r.pointId===point?.id&&r.variable==='current')?.limit??null}/><section className="panel"><h2>{point?.name||'Sin puntos'}</h2><dl><dt>Sensor</dt><dd>Kistler M715A simulado</dd><dt>Módulo</dt><dd>ESP32-S3 simulado</dd><dt>Voltaje configurado</dt><dd>{point?.voltage} V</dd><dt>Factor de potencia</dt><dd>{point?.pf}</dd><dt>Intervalo</dt><dd>{point?.interval} segundos</dd><dt>Comunicación</dt><dd>{point?.communication}</dd><dt>Última recepción</dt><dd>{time(point?.lastReceived)}</dd></dl></section></div><section className="panel"><h2>Lecturas recibidas <small>Últimas 300 del filtro</small></h2><Table heads={['Medición','Corriente A','Potencia kW','Energía intervalo kWh','Recepción','Calidad']} rows={pointRows.map(m=>[time(m.at),fmt(m.current),fmt(m.power),fmt(m.energyDelta,6),time(m.receivedAt),<Badge tone={m.outside.length?'warn':''}>{m.outside.length?'Fuera de umbral':'Simulado'}</Badge>])}/></section></>;
 if(view==='assets')content=<><div className="tabs">{['Puntos','Áreas','Diagnóstico'].map((t,i)=><button className={tab===i?'active':''} key={t} onClick={()=>setTab(i)}>{t}</button>)}</div><section className="panel"><div className="panel-title"><h2>{['Puntos de medición','Áreas del edificio','Diagnóstico de adquisición'][tab]}</h2>{admin&&tab<2&&<button className="primary" onClick={()=>setEditor({type:tab===0?'point':'area',values:tab===0?{id:'',name:'',areaId:data.areas[0]?.id,baseCurrent:8,voltage:120,pf:0.95,interval:5,active:true}:{id:'',name:''}})}>+ Crear {tab===0?'punto':'área'}</button>}</div>{tab===0?pointTable(admin):tab===1?<Table heads={['Identificador','Área','Puntos','Acción']} rows={data.areas.map(a=>[a.id,a.name,data.points.filter(p=>p.areaId===a.id).length,admin?<button onClick={()=>setEditor({type:'area',values:{...a,edit:true}})}>Editar</button>:'Lectura'])}/>:<Table heads={['Punto','Esperadas','Recibidas','Última secuencia','Estado']} rows={data.points.map(p=>[p.id,p.expected,p.received,p.lastSequence??'Sin datos',p.communication])}/>}</section></>;
 if(view==='events')content=<><div className="metrics"><Card title="ABIERTAS" value={data.events.filter(e=>e.status==='Abierta').length} tone="amber"/><Card title="EN REVISIÓN" value={data.events.filter(e=>e.status==='En revisión').length}/><Card title="CERRADAS" value={data.events.filter(e=>e.status==='Cerrada').length} tone="green"/></div><section className="panel"><h2>Eventos detectados</h2><Table heads={['Inicio','Punto','Regla','Severidad','Estado','Acción']} rows={data.events.map(e=>[time(e.start),e.pointId,e.ruleId,<Badge tone="warn">{e.severity}</Badge>,e.status,<button onClick={()=>setEvent(e.id)}>Ver evidencia</button>])}/></section>{event&&(()=>{const e=data.events.find(e=>e.id===event);if(!e)return null;return <section className="panel"><h2>Evidencia · {e.pointId}</h2><p>Condición: {vars[e.variable]} {e.operator} {e.limit} {units[e.variable]} · {e.end?'Condición recuperada: '+time(e.end):'Condición todavía activa'}</p><Chart rows={data.measurements.filter(m=>e.evidence.includes(m.id))} variable={e.variable} unit={units[e.variable]} title="Lecturas del evento" threshold={e.limit}/><Table heads={['Fecha','Usuario','Estado','Observación']} rows={e.history.map(h=>[time(h.at),h.user,h.status,h.note])}/>{admin&&e.status!=='Cerrada'&&<form className="filters" onSubmit={ev=>{ev.preventDefault();const f=new FormData(ev.target);save('/api/events',{id:e.id,status:f.get('status'),note:f.get('note')});}}><Field label="Seguimiento"><select name="status"><option>En revisión</option><option disabled={!e.end}>Cerrada</option></select></Field><Field label="Observación obligatoria"><input name="note" required maxLength="200"/></Field><button className="primary" disabled={busy}>Guardar seguimiento</button></form>}</section>;})()}</>;
 if(view==='rules')content=<section className="panel"><div className="panel-title"><h2>Condiciones de detección</h2>{admin&&<button className="primary" onClick={()=>setEditor({type:'rule',values:{pointId:data.points[0]?.id,variable:'current',operator:'>',limit:12,persistence:2,severity:'Alta',active:true}})}>+ Crear regla</button>}</div><p className="muted">La persistencia requiere lecturas consecutivas. Los huecos de comunicación interrumpen el conteo.</p><Table heads={['Regla','Punto','Condición','Persistencia','Severidad','Estado','Acción']} rows={data.rules.map(r=>[r.id,r.pointId,`${vars[r.variable]} ${r.operator} ${r.limit} ${units[r.variable]}`,`${r.persistence} lecturas`,r.severity,r.active?'Activa':'Inactiva',admin?<button onClick={()=>setEditor({type:'rule',values:r})}>Editar</button>:'Lectura'])}/></section>;
 if(view==='analysis')content=<>{commonFilters}<div className="tabs">{['Energéticos 01–08','Detección 09–14','Sistema 15–17'].map((t,i)=><button key={t} className={tab===i?'active':''} onClick={()=>setTab(i)}>{t}</button>)}</div><div className="indicator-grid">{data.analysis.indicators.filter(i=>tab===0?i.id<=8:tab===1?i.id>=9&&i.id<=14:i.id>=15).map(i=><article className="panel" key={i.id}><small>{String(i.id).padStart(2,'0')} · {i.name}</small><h2 className="indicator-value">{num(i.value)} <small>{i.unit}</small></h2><details><summary>Fórmula y fuente</summary><p>{i.formula}</p><p>Fuente: registros recibidos o emisiones del simulador, según el indicador. {data.analysis.rows} lecturas en el filtro.</p></details></article>)}</div><section className="panel"><h2>Consumo diario registrado</h2><Table heads={['Fecha local','Energía kWh']} rows={Object.entries(data.analysis.daily).map(([d,v])=>[d,fmt(v,6)])}/><p className="muted">Los días pueden tener cobertura parcial. Reducción, variación y tendencia requieren fechas delimitadas y registros en el período anterior equivalente.</p></section></>;
 if(view==='reports')content=<>{commonFilters}{canReport&&<section className="panel"><h2>Generar informe</h2><form className="filters" onSubmit={e=>{e.preventDefault();save('/api/reports?'+query(),{title:new FormData(e.target).get('title')});}}><Field label="Título del informe"><input name="title" required defaultValue="Informe de consumo energético"/></Field><button className="primary" disabled={busy}>Generar PDF y CSV</button></form><p className="muted">El informe conservará filtros, origen, cobertura y los 17 indicadores disponibles al generarlo.</p></section>}<section className="panel"><h2>Catálogo de informes</h2><Table heads={['Informe','Generado','Autor','Cobertura','Descargas']} rows={data.reports.map(r=>[r.title,time(r.at),r.author,`${num(r.coverage)} %`,<div className="actions"><a className="button" href={`/api/reports/${r.id}/pdf`}>PDF</a><a className="button" href={`/api/reports/${r.id}/csv`}>CSV</a></div>])}/></section></>;
 if(view==='simulation'&&admin)content=<><section className="simulation-banner"><div><Badge>ORIGEN SIMULADO</Badge><h2>{data.health.running?'Simulación en ejecución':'Simulación pausada'}</h2><p>Puntos virtuales → broker MQTT local → validación → almacenamiento → interfaz</p></div><button className="primary" disabled={busy} onClick={()=>save('/api/simulation',{running:!data.health.running})}>{data.health.running?'Pausar simulación':'Iniciar simulación'}</button></section><div className="metrics"><Card title="MENSAJES ESPERADOS" value={data.health.expected}/><Card title="MENSAJES RECIBIDOS" value={data.health.received} tone="green"/><Card title="EN COLA" value={data.health.queued} tone="amber"/></div><section className="panel"><h2>Escenarios por punto</h2><p className="muted">Sobrecarga: 2.3 veces la corriente base. Sin consumo: 0 A. Desconexión: ninguna transmisión. La latencia y la pérdida se aplican antes del envío MQTT.</p><Table heads={['Punto','Escenario','Pérdida','Latencia','Muestreo','Acción']} rows={data.points.map(p=>[<><b>{p.id}</b><small className="block">{p.name}</small></>,p.scenario,`${p.loss} %`,`${p.delay} ms`,`${p.interval} s`,<button onClick={()=>setEditor({type:'simulation',values:{pointId:p.id,scenario:p.scenario,loss:p.loss,delay:p.delay}})}>Configurar</button>])}/></section><section className="panel"><h2>Registro de comunicación</h2><Table heads={['Fecha','Punto','Secuencia','Resultado','Detalle']} rows={data.transport.map(t=>[time(t.at),t.pointId||'—',t.seq??'—',<Badge tone={t.status==='Recibido'?'good':'warn'}>{t.status}</Badge>,t.detail])}/></section></>;
 if(view==='users'&&admin)content=<><section className="panel"><div className="panel-title"><h2>Cuentas de acceso</h2><button className="primary" onClick={()=>setEditor({type:'user',values:{username:'',name:'',role:'Consulta',active:true,password:''}})}>+ Crear usuario</button></div><Table heads={['Usuario','Nombre','Grupo','Estado','Acción']} rows={data.users.map(u=>[u.username,u.name,u.role,u.active?'Activo':'Inactivo',<button onClick={()=>setEditor({type:'user',values:{...u,password:''}})}>Editar</button>])}/></section><section className="panel"><h2>Matriz de permisos</h2><Table heads={['Función','Administrador','Técnico','Consulta']} rows={[["Consultar monitoreo e indicadores","✓","✓","✓"],["Generar informes","✓","✓","—"],["Descargar informes existentes","✓","✓","✓"],["Editar activos, reglas y anomalías","✓","—","—"],["Configurar simulación y usuarios","✓","—","—"]]}/></section></>;
 if(view==='settings'&&admin)content=<><div className="metrics"><Card title="BASE DE DATOS" value={data.health.database} hint="Almacenamiento persistente"/><Card title="MQTT LOCAL" value={data.health.mqtt?'Conectado':'Sin conexión'} tone="green"/><Card title="DIAGNÓSTICO" value={data.health.lastError?'Error':'Operativo'} hint={data.health.lastError||'Sin errores registrados'}/></div><section className="panel"><div className="panel-title"><h2>Parámetros del sistema</h2><button onClick={()=>setEditor({type:'settings',values:data.settings})}>Editar configuración</button></div><dl><dt>Vigencia</dt><dd>{data.settings.staleIntervals} intervalos por punto</dd><dt>Zona horaria</dt><dd>{data.settings.timezone}</dd><dt>Tarifa ilustrativa</dt><dd>Q {fmt(data.settings.tariff)} / kWh</dd></dl><p className="muted">La tarifa es un parámetro de demostración. Los intervalos se configuran en Activos y áreas.</p></section><section className="panel"><h2>Registro de actividad</h2><Table heads={['Fecha','Cuenta','Acción']} rows={data.audit.map(a=>[time(a.at),a.user,a.action])}/></section></>;
 return <div className="app"><aside className={mobile?'sidebar show':'sidebar'}><div className="brand">ENERGÍA<span>CONTROL Y ANÁLISIS</span></div><nav>{nav.filter(([id])=>admin||!['users','settings','simulation'].includes(id)).map(([id,label,icon])=><button key={id} aria-label={label} className={view===id?'selected':''} onClick={()=>go(id)}><i>{icon}</i>{label}</button>)}</nav><div className="sidebar-bottom">PG2 · PROGRAMA FUNCIONAL<Badge>SIMULACIÓN</Badge></div></aside><div className="workspace"><header><button className="menu-toggle" onClick={()=>setMobile(!mobile)}>☰</button><b>Sistema de monitoreo energético</b><div className="header-right"><Badge>SIMULADO</Badge><span>{data.user.name}<small>{data.user.role}</small></span><button onClick={async()=>{await request('/api/logout',{});setAuth(false);setData(null);}}>Salir</button></div></header><main><div className="page-heading"><div><h1>{nav.find(n=>n[0]===view)?.[1]}</h1><p>Edificio Monja Blanca · MAGA <span className="separator">/</span> Entrega 5.1</p></div><span className="live-dot">{data.health.running?'Simulando':'Pausado'}</span></div>{error&&<div className="alert" role="alert">{error} <button onClick={refresh}>Reintentar</button></div>}{toast&&<div className="toast" role="status">{toast}</div>}{content}<footer>Datos simulados · Sin conexión a hardware · Potencia y energía calculadas con parámetros de simulación.</footer></main></div>{editor&&<Editor editor={editor} data={data} busy={busy} error={error} close={()=>{setEditor(null);setError('');}} save={save}/>}</div>;
}
function Editor({editor,data,busy,error,close,save}){
 const [v,setV]=useState({...editor.values});const set=(k,val)=>setV({...v,[k]:val});const {type}=editor;
 const input=(k,label,kind='text',props={})=><Field label={label}><input {...props} type={kind} value={v[k]??''} onChange={e=>set(k,kind==='number'?Number(e.target.value):e.target.value)}/></Field>;
 const select=(k,label,options)=><Field label={label}><select value={v[k]} onChange={e=>set(k,e.target.value)}>{options.map(o=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select></Field>;
 const active=<label className="checkbox"><input type="checkbox" checked={!!v.active} onChange={e=>set('active',e.target.checked)}/> Activo</label>;
 const titles={point:'Punto de medición',area:'Área del edificio',rule:'Regla de detección',simulation:'Escenario de simulación',user:'Cuenta de usuario',settings:'Parámetros de operación'};
 const routes={point:'/api/points',area:'/api/areas',rule:'/api/rules',simulation:'/api/simulation',user:'/api/users',settings:'/api/settings'};
 return <div className="overlay"><section className="drawer" role="dialog" aria-modal="true" aria-label={titles[type]}><div className="panel-title"><h2>{titles[type]}</h2><button onClick={close} aria-label="Cerrar">×</button></div>{error&&<div role="alert" className="alert">{error}</div>}<form onSubmit={e=>{e.preventDefault();save(routes[type],v);}}>
 {type==='area'&&<>{input('id','Identificador único','text',{required:true,disabled:v.edit})}{input('name','Nombre','text',{required:true})}</>}
 {type==='point'&&<>{input('id','Identificador único','text',{required:true,disabled:v.edit})}{input('name','Nombre del punto','text',{required:true})}{select('areaId','Área',data.areas.map(a=>[a.id,a.name]))}{input('baseCurrent','Corriente base (A)','number',{min:0,max:1000,step:'any',required:true})}{input('voltage','Voltaje simulado (V)','number',{min:1,max:1000,step:'any',required:true})}{input('pf','Factor de potencia','number',{min:0.01,max:1,step:'any',required:true})}{input('interval','Intervalo de envío (s)','number',{min:1,max:3600,required:true})}{active}<p className="muted">La inactivación conserva el historial. Un cambio de parámetros inicia un nuevo intervalo de integración.</p></>}
 {type==='rule'&&<>{select('pointId','Punto',data.points.map(p=>[p.id,p.id+' · '+p.name]))}{select('variable','Variable',Object.entries(vars))}{select('operator','Operador',[['>','Mayor que'],['<','Menor que']])}{input('limit',`Límite (${units[v.variable]})`,'number',{min:0,step:'any',required:true})}{input('persistence','Persistencia (lecturas)','number',{min:1,step:1,required:true})}{select('severity','Severidad',[['Alta','Alta'],['Media','Media'],['Baja','Baja']])}{active}<div className="preview">{vars[v.variable]} {v.operator} {v.limit} {units[v.variable]} durante {v.persistence} lecturas consecutivas.</div></>}
 {type==='simulation'&&<><p><b>{v.pointId}</b> · Configuración de transmisión</p>{select('scenario','Escenario',[['normal','Consumo normal'],['sobrecarga','Sobrecarga'],['sin_consumo','Sin consumo'],['desconexion','Desconexión']])}{input('loss','Pérdida de mensajes (%)','number',{min:0,max:100,required:true})}{input('delay','Latencia de envío (ms)','number',{min:0,max:60000,step:100,required:true})}<p className="muted">Los mensajes perdidos no ingresan al backend. Los retrasados se conservan en una cola temporal.</p></>}
 {type==='user'&&<>{input('username','Usuario único','text',{required:true})}{input('name','Nombre','text',{required:true})}{select('role','Grupo',[['Administrador','Administrador'],['Técnico','Técnico'],['Consulta','Consulta']])}{input('password',v.id?'Nueva contraseña (opcional)':'Contraseña','password',{minLength:10,required:!v.id,autoComplete:'new-password'})}{active}<p className="muted">Modificar una cuenta invalida sus sesiones. Debe conservarse un administrador activo.</p></>}
 {type==='settings'&&<>{input('staleIntervals','Vigencia de comunicación (intervalos)','number',{min:1,max:100,required:true})}{input('timezone','Zona horaria','text',{required:true})}{input('tariff','Tarifa ilustrativa (Q/kWh)','number',{min:0,max:100,step:'any',required:true})}</>}
 <div className="drawer-actions"><button type="button" onClick={close}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar cambios'}</button></div></form></section></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
